name: Firebase Deploy (Hosting + Functions)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth with Google
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Install Functions deps
        working-directory: functions
        run: npm ci || npm install

      - name: Deploy to Firebase
        run: firebase deploy --only hosting,functions --project tomstom-8 --non-interactive
